CREATE TABLE imagery_images (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    -- author_id INTEGER
    --     REFERENCES imagery_users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);