CREATE TABLE imagery_images (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);