CREATE TABLE imagery_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() not null,
    date_modified TIMESTAMP
)
ALTER TABLE imagery_images
    ADD COLUMN
        author_id INTEGER REFERENCES imagery_users(id)
        ON DELETE SET NULL;
